# Generated by Django 5.2.1 on 2025-07-01 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussionpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='discussion_images/'),
        ),
        migrations.AddField(
            model_name='discussionpost',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
