# Generated by Django 5.2.1 on 2025-07-02 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_discussionpost_dislikes_discussionpost_likes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussionpost',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
