# Generated by Django 5.2.1 on 2025-07-22 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_discussionpost_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelfAssessmentReturn',
            fields=[
                ('submission_no', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, verbose_name='Username')),
                ('password', models.CharField(max_length=128, verbose_name='Password')),
                ('password2', models.CharField(max_length=128, verbose_name='Confirm Password')),
                ('pan_no', models.CharField(max_length=20, verbose_name='PAN No.')),
                ('fiscal_year', models.CharField(max_length=9, verbose_name='Fiscal Year')),
                ('email', models.EmailField(max_length=254, verbose_name='Email ID')),
                ('contact_no', models.CharField(max_length=20, verbose_name='Contact No.')),
                ('turnover_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='कर कारोबार रकम')),
                ('deduction_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='कट्टी हुने रकम')),
                ('income', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='आय (auto)')),
                ('tax_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Tax (auto)')),
                ('interest_penalty', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Interest & Penalty (auto)')),
                ('total_payable', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Total Payable (auto)')),
                ('revenue_account_no', models.CharField(max_length=50, verbose_name='राजश्व खाता नं.')),
                ('payment_type', models.CharField(max_length=50, verbose_name='भुक्तानीको किसिम')),
                ('voucher_no', models.CharField(max_length=50, verbose_name='भौचर/रसिद नं.')),
                ('bank_name', models.CharField(max_length=100, verbose_name='बैंकको नाम')),
                ('deposit_date', models.DateField(verbose_name='दाखिला मिति')),
                ('deposit_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='दाखिला रकम')),
                ('submitted', models.BooleanField(default=False)),
                ('receipt', models.FileField(blank=True, null=True, upload_to='tax_receipts/', verbose_name='Payment Receipt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-submission_no'],
            },
        ),
    ]
