# Generated by Django 5.2.1 on 2025-07-22 07:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_selfassessmentreturn'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pan_no', models.CharField(max_length=50, verbose_name='PAN Number')),
                ('fiscal_year', models.CharField(max_length=9, verbose_name='Fiscal Year')),
                ('email', models.EmailField(max_length=254)),
                ('contact_no', models.CharField(max_length=20, verbose_name='Contact No')),
                ('turnover_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('deduction_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('revenue_account_no', models.CharField(max_length=50)),
                ('payment_type', models.CharField(max_length=50)),
                ('voucher_no', models.CharField(max_length=50)),
                ('bank_name', models.CharField(max_length=100)),
                ('deposit_date', models.DateField()),
                ('deposit_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('receipt', models.FileField(blank=True, help_text='Upload your payment receipt', null=True, upload_to='tax_receipts/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
