# Generated by Django 5.2.1 on 2025-07-22 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_taxreturn'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Hospital Name')),
                ('allocated_beds', models.PositiveIntegerField(verbose_name='Allocated Beds')),
                ('total_beds', models.PositiveIntegerField(verbose_name='Total Beds')),
                ('active_patients', models.PositiveIntegerField(verbose_name='Active Patients')),
                ('hospital_type', models.CharField(choices=[('Community', 'Community'), ('Private', 'Private'), ('Government', 'Government')], max_length=20, verbose_name='Hospital Type')),
                ('contact_person', models.CharField(max_length=100, verbose_name='Contact Person')),
                ('contact_number', models.CharField(max_length=20, verbose_name='Contact Number')),
            ],
            options={
                'verbose_name': 'Hospital',
                'verbose_name_plural': 'Hospitals',
            },
        ),
    ]
